// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: account_manager.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountRequestGrpc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Address   string `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	City      string `protobuf:"bytes,5,opt,name=City,proto3" json:"City,omitempty"`
	State     string `protobuf:"bytes,6,opt,name=State,proto3" json:"State,omitempty"`
	Phone     string `protobuf:"bytes,7,opt,name=Phone,proto3" json:"Phone,omitempty"`
}

func (x *AccountRequestGrpc) Reset() {
	*x = AccountRequestGrpc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRequestGrpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequestGrpc) ProtoMessage() {}

func (x *AccountRequestGrpc) ProtoReflect() protoreflect.Message {
	mi := &file_account_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequestGrpc.ProtoReflect.Descriptor instead.
func (*AccountRequestGrpc) Descriptor() ([]byte, []int) {
	return file_account_manager_proto_rawDescGZIP(), []int{0}
}

func (x *AccountRequestGrpc) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AccountRequestGrpc) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AccountRequestGrpc) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountRequestGrpc) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AccountRequestGrpc) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AccountRequestGrpc) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AccountRequestGrpc) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ResponseGrpc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int64  `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *ResponseGrpc) Reset() {
	*x = ResponseGrpc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGrpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGrpc) ProtoMessage() {}

func (x *ResponseGrpc) ProtoReflect() protoreflect.Message {
	mi := &file_account_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGrpc.ProtoReflect.Descriptor instead.
func (*ResponseGrpc) Descriptor() ([]byte, []int) {
	return file_account_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseGrpc) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResponseGrpc) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_account_manager_proto protoreflect.FileDescriptor

var file_account_manager_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xbe, 0x01, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x47, 0x72, 0x70, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x22, 0x48, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x72, 0x70,
	0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4e, 0x0a, 0x0e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x3c, 0x0a,
	0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x47, 0x72, 0x70, 0x63, 0x1a, 0x15, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x72, 0x70, 0x63, 0x42, 0x13, 0x5a, 0x11, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_manager_proto_rawDescOnce sync.Once
	file_account_manager_proto_rawDescData = file_account_manager_proto_rawDesc
)

func file_account_manager_proto_rawDescGZIP() []byte {
	file_account_manager_proto_rawDescOnce.Do(func() {
		file_account_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_manager_proto_rawDescData)
	})
	return file_account_manager_proto_rawDescData
}

var file_account_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_manager_proto_goTypes = []interface{}{
	(*AccountRequestGrpc)(nil), // 0: account.AccountRequestGrpc
	(*ResponseGrpc)(nil),       // 1: account.ResponseGrpc
}
var file_account_manager_proto_depIdxs = []int32{
	0, // 0: account.AccountManager.Create:input_type -> account.AccountRequestGrpc
	1, // 1: account.AccountManager.Create:output_type -> account.ResponseGrpc
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_manager_proto_init() }
func file_account_manager_proto_init() {
	if File_account_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_account_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRequestGrpc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGrpc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_manager_proto_goTypes,
		DependencyIndexes: file_account_manager_proto_depIdxs,
		MessageInfos:      file_account_manager_proto_msgTypes,
	}.Build()
	File_account_manager_proto = out.File
	file_account_manager_proto_rawDesc = nil
	file_account_manager_proto_goTypes = nil
	file_account_manager_proto_depIdxs = nil
}
