name: 4 - Lambda Email Notifier

on:
  workflow_call:
    inputs:
      folder_default:
        required: true
        type: string

jobs:
  development:
    if: startsWith(github.ref, 'refs/tags/v') == false
    uses: ./.github/workflows/template-simple.yml
    secrets: inherit
    with:
      environment: ReleaseDevelopment
      lambda_name: EmailNotifier
      folder_default: ${{ inputs.folder_default }}

  staging:
    needs: development
    if: startsWith(github.ref, 'refs/tags/v') == false
    uses: ./.github/workflows/template-simple.yml
    secrets: inherit
    with:
      environment: ReleaseStaging
      lambda_name: EmailNotifier
      folder_default: ${{ inputs.folder_default }}

  release:
    needs: staging
    if: startsWith(github.ref, 'refs/tags/v') == false
    uses: ./.github/workflows/template-simple.yml
    secrets: inherit
    with:
      environment: Release
      lambda_name: EmailNotifier
      folder_default: ${{ inputs.folder_default }}